# Site settings
title: Blog Pribadi Riki Mardiyanto
header-img: img/home-bg.jpg
email: rikimardiyanto11@gmail.com
copyright_name: RikiMardiyanto Blog
description: "Halaman ini merupakan blog pribadi saya yang membahas berbagai topik yang semoga bermanfaat bagi kita semuanya !"
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://rikimardiyanto.github.io"
twitter_username: rikimardiyanto
github_username:  rikimardiyanto
facebook_username:  Ricky Ackerman
email_username:  your-email@yourdomain.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
